# Package definition for __PKG_NAME__

package_name: __PKG_NAME__
github_repo: __GITHUB_REPO__
artifact_format: __ARTIFACT_FORMAT__
description: "__DESCRIPTION__"
license: __LICENSE__

# Build for all Debian suites and all supported architectures.
